[files]
extend-exclude = [
  "ci/checks/*",
  "graphics/*.cast",
  "graphics/generate-asciinema-gif",
]

[default.extend-words]
urrent = "urrent"  # to allow for `c[urrent]`
tatus = "tatus"  # to allow for `s[tatus]`
ther = "ther"  # to allow for `o[ther]`
typ = "typ"  # to allow for `typ[e]`
