services:
  nixpkgs:
    image: gitmachete/ci-nixpkgs:${DIRECTORY_HASH:-unspecified}
    platform: linux/amd64
    build:
      context: build-context
      dockerfile: ../Dockerfile # relative to build-context
    tty: true
    environment:
      - GIT_REVISION
